language: node_js
node_js:
    - "6"
before_script:
    - npm install sequelize-cli -g
    - psql -c "CREATE DATABASE postit-test;" -U postgres
    - sequelize db:migrate --env test
script: npm test
after_success:
    -npm run coveralls
services:
    - postgres        
env:
    global:
        -NODE_ENV=test